### ISSUE TITLE
请问执行教程中的爬取CSDN博客原码出错

### ISSUE THREAD

**Issue by dyn1721** [CrawlScript/WebCollector#115]
代码没改 出错情况：
java.io.IOException: gzip finished without exhausting source
	at okio.GzipSource.read(GzipSource.java:100)
	at okio.Buffer.writeAll(Buffer.java:1053)
	at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:108)
	at okhttp3.ResponseBody.bytes(ResponseBody.java:137)
	at cn.edu.hfut.dmic.webcollector.plugin.net.OkHttpRequester.getResponse(OkHttpRequester.java:114)
	at cn.edu.hfut.dmic.webcollector.crawler.AutoParseCrawler.execute(AutoParseCrawler.java:87)
	at cn.edu.hfut.dmic.webcollector.fetcher.Fetcher$FetcherThread.run(Fetcher.java:245)

**Comment by jack13163** [comment]
将package cn.edu.hfut.dmic.webcollector.plugin.net;中的createRequestBuilder中加入：
builder.addHeader("Accept-Encoding", "gzip, deflate");
网上的解释是：
默认情况下,OkHttpClient默认对请求和返回数据进行"gzip"的自动解压缩的,而发生这个异常的原因是：服务器返回数据的时候，自动将gzip的数据解压了，导致okhttpclient在去解压的时候发现流已经被读完了
地址：https://blog.csdn.net/u013887008/article/details/102618961
