### ISSUE TITLE
断点爬取怎么感觉每次都会重新爬取一次呢

### ISSUE THREAD

**Issue by jinfanw** [CrawlScript/WebCollector#25]
你好，在爬取一段时间后，终端爬虫，再重新进行时，还会把相同的页面爬取下来。
每次输出的title都会出现相同的。   crawler.setResumable(true) ，设置true或者false，效果一样
是我设置的问题吗?多谢指教。附部分代码
@Override
    public void visit(Page page, CrawlDatums next) {		
        System.out.println("<<<<<<<<<<visiting:"+page.getUrl()+"\tdepth="+page.getMetaData("depth"));
        String title = page.select("title").first().text();
        System.out.println(title);  	
    }

    /* afterVisit方法在visit方法执行后执行，这里super.afterVisit完成根据
       正则自动抽取链接的功能，因此这里需要保留 */
    @Override
    public void afterVisit(Page page, CrawlDatums next) {
        super.afterVisit(page, next); 
        
        //当前页面的depth为x，则从当前页面解析的后续任务的depth为x+1
        int depth;
        //如果在添加种子时忘记添加depth信息，可以通过这种方式保证程序不出错
        if(page.getMetaData("depth")==null){
            depth=1;
        }else{
            depth=Integer.valueOf(page.getMetaData("depth"));
        }
        depth++;
        for(CrawlDatum datum:next){
            datum.putMetaData("depth", depth+"");
        }
    }
    
    public static void main(String[] args) throws Exception {
        Example crawler=new Example("example_crawler", true);
       
        crawler.addSeed(new CrawlDatum("http://news.sohu.com/")
               .putMetaData("depth", "1"));
        
        crawler.addRegex(".*news.sohu.com/.*.shtml");
        crawler.setRetryInterval(1000);
        crawler.setVisitInterval(1000*1);
        crawler.setThreads(1);
        crawler.setResumable(true);
     
        crawler.start(3);
    }

**Comment by hujunxianligong** [comment]
title相同有可能url不相同，爬虫会将http://news.sohu.com/和http://news.sohu.com认为是不同的两个页面。请调试查看url是否相同。

**Comment by jinfanw** [comment]
你好，我刚才确认了一下，url是一样的。
不知道是不是有什么地方需要在设置吗？

**Comment by jinfanw** [comment]
我是一个网站没全爬取，只取了10多条数据，不知道这个写入库是不是有延迟？

**Comment by hujunxianligong** [comment]
发一下完整代码和日志

**Comment by jinfanw** [comment]
代码：
package com.jintian.crawler;

import java.io.IOException;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.regex.Pattern;

import cn.edu.hfut.dmic.webcollector.model.CrawlDatum;
import cn.edu.hfut.dmic.webcollector.model.CrawlDatums;
import cn.edu.hfut.dmic.webcollector.model.Page;
import cn.edu.hfut.dmic.webcollector.plugin.berkeley.BreadthCrawler;
import cn.edu.hfut.dmic.webcollector.util.FileUtils;

public class SingerFetch extends BreadthCrawler{
	
	public SingerFetch(String crawlPath, boolean autoParse) {
		super(crawlPath, autoParse);
	}
	
	AtomicInteger id=new AtomicInteger(0);
	
	@Override
    public void visit(Page page, CrawlDatums next) {
		
        System.out.println("<<<<<<<<<<visiting:"+page.getUrl()+"\tdepth="+page.getMetaData("depth"));
        String title = page.select("title").first().text();
        System.out.println(title);
       }

    /* afterVisit方法在visit方法执行后执行，这里super.afterVisit完成根据
       正则自动抽取链接的功能，因此这里需要保留 */
    @Override
    public void afterVisit(Page page, CrawlDatums next) {
        super.afterVisit(page, next); 
        
        //当前页面的depth为x，则从当前页面解析的后续任务的depth为x+1
        int depth;
        //如果在添加种子时忘记添加depth信息，可以通过这种方式保证程序不出错
        if(page.getMetaData("depth")==null){
            depth=1;
        }else{
            depth=Integer.valueOf(page.getMetaData("depth"));
        }
        depth++;
        for(CrawlDatum datum:next){
            datum.putMetaData("depth", depth+"");
        }
    }
    
    public static void main(String[] args) throws Exception {
        Example crawler=new Example("single_crawler", true);
       
        crawler.addSeed(new CrawlDatum("http://news.sohu.com/")
               .putMetaData("depth", "1"));

             
        crawler.addRegex(".*news.sohu.com/.*.shtml");
        crawler.setRetryInterval(1000);
        crawler.setVisitInterval(1000*1);
        crawler.setThreads(1);
        crawler.setResumable(true);

        crawler.start(3);
    }

}

**Comment by jinfanw** [comment]
第一次日志：
2016-01-02 14:43:28 INFO cn.edu.hfut.dmic.webcollector.crawler.Crawler  - start depth 1
2016-01-02 14:43:28 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - open generator:cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyGenerator
2016-01-02 14:43:28 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - init segmentWriter:cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBManager
2016-01-02 14:43:28 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - fetch URL: http://news.sohu.com/
<<<<<<<<<<visiting:http://news.sohu.com/	depth=1
搜狐新闻-搜狐
2016-01-02 14:43:29 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - -activeThreads=1, spinWaiting=0, fetchQueue.size=0
2016-01-02 14:43:30 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - -activeThreads=1, spinWaiting=0, fetchQueue.size=0
2016-01-02 14:43:31 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - -activeThreads=0, spinWaiting=0, fetchQueue.size=0
2016-01-02 14:43:31 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - clear all activeThread
2016-01-02 14:43:31 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - close generator:cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyGenerator
2016-01-02 14:43:31 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - close segmentwriter:cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBManager
2016-01-02 14:43:31 INFO cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBManager  - start merge
2016-01-02 14:43:31 INFO cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBManager  - merge fetch database
2016-01-02 14:43:31 INFO cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBManager  - merge link database
2016-01-02 14:43:31 INFO cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBManager  - end merge
2016-01-02 14:43:31 INFO cn.edu.hfut.dmic.webcollector.crawler.Crawler  - depth 1 finish: 
	TOTAL urls:	1
	TOTAL time:	3 seconds
2016-01-02 14:43:31 INFO cn.edu.hfut.dmic.webcollector.crawler.Crawler  - start depth 2
2016-01-02 14:43:31 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - open generator:cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyGenerator
2016-01-02 14:43:31 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - init segmentWriter:cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBManager
2016-01-02 14:43:31 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - fetch URL: http://news.sohu.com/20140115/n393575818.shtml
<<<<<<<<<<visiting:http://news.sohu.com/20140115/n393575818.shtml	depth=2
支教女孩黄兰练患尿毒症急需50万医药费 -搜狐新闻
2016-01-02 14:43:32 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - -activeThreads=1, spinWaiting=0, fetchQueue.size=142
2016-01-02 14:43:32 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - fetch URL: http://news.sohu.com/20140803/n403047045.shtml
<<<<<<<<<<visiting:http://news.sohu.com/20140803/n403047045.shtml	depth=2
习近平对事故作重要指示-搜狐新闻
2016-01-02 14:43:33 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - -activeThreads=1, spinWaiting=0, fetchQueue.size=141
2016-01-02 14:43:33 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - fetch URL: http://news.sohu.com/20140804/n403071477.shtml
<<<<<<<<<<visiting:http://news.sohu.com/20140804/n403071477.shtml	depth=2
习近平对云南昭通鲁甸县地震作出重要指示批示-搜狐新闻
2016-01-02 14:43:34 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - -activeThreads=1, spinWaiting=0, fetchQueue.size=140
2016-01-02 14:43:34 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - fetch URL: http://news.sohu.com/20141126/n406390003.shtml
<<<<<<<<<<visiting:http://news.sohu.com/20141126/n406390003.shtml	depth=2
河北再拒聂树斌案阅卷请求 被指每天有新理由拖延-搜狐新闻
2016-01-02 14:43:35 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - -activeThreads=1, spinWaiting=0, fetchQueue.size=139
2016-01-02 14:43:35 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - fetch URL: http://news.sohu.com/20141126/n406399379.shtml
<<<<<<<<<<visiting:http://news.sohu.com/20141126/n406399379.shtml	depth=2
河北唐山现最牛婚礼 30多辆豪车价值超2亿(图)-搜狐新闻
2016-01-02 14:43:36 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - -activeThreads=1, spinWaiting=0, fetchQueue.size=138
2016-01-02 14:43:37 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - fetch URL: http://news.sohu.com/20150331/n410569699.shtml
<<<<<<<<<<visiting:http://news.sohu.com/20150331/n410569699.shtml	depth=2
盘点“低头族”?事：男子过铁道看手机逼停火车-搜狐新闻

**Comment by jinfanw** [comment]
第二次日志：
2016-01-02 14:44:23 INFO cn.edu.hfut.dmic.webcollector.crawler.Crawler  - start depth 1
2016-01-02 14:44:23 INFO cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBManager  - start merge
2016-01-02 14:44:23 INFO cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBManager  - merge fetch database
2016-01-02 14:44:23 INFO cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBManager  - merge link database
2016-01-02 14:44:23 INFO cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBManager  - end merge
2016-01-02 14:44:23 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - open generator:cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyGenerator
2016-01-02 14:44:23 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - init segmentWriter:cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBManager
2016-01-02 14:44:24 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - fetch URL: http://news.sohu.com/20140115/n393575818.shtml
<<<<<<<<<<visiting:http://news.sohu.com/20140115/n393575818.shtml	depth=2
支教女孩黄兰练患尿毒症急需50万医药费 -搜狐新闻
2016-01-02 14:44:24 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - -activeThreads=1, spinWaiting=0, fetchQueue.size=142
2016-01-02 14:44:25 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - fetch URL: http://news.sohu.com/20140803/n403047045.shtml
<<<<<<<<<<visiting:http://news.sohu.com/20140803/n403047045.shtml	depth=2
习近平对事故作重要指示-搜狐新闻
2016-01-02 14:44:25 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - -activeThreads=1, spinWaiting=0, fetchQueue.size=141
2016-01-02 14:44:26 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - -activeThreads=1, spinWaiting=0, fetchQueue.size=140
2016-01-02 14:44:26 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - fetch URL: http://news.sohu.com/20140804/n403071477.shtml
<<<<<<<<<<visiting:http://news.sohu.com/20140804/n403071477.shtml	depth=2
习近平对云南昭通鲁甸县地震作出重要指示批示-搜狐新闻
2016-01-02 14:44:27 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - -activeThreads=1, spinWaiting=0, fetchQueue.size=140
2016-01-02 14:44:28 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - fetch URL: http://news.sohu.com/20141126/n406390003.shtml
<<<<<<<<<<visiting:http://news.sohu.com/20141126/n406390003.shtml	depth=2
河北再拒聂树斌案阅卷请求 被指每天有新理由拖延-搜狐新闻
2016-01-02 14:44:28 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - -activeThreads=1, spinWaiting=0, fetchQueue.size=139
2016-01-02 14:44:29 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - fetch URL: http://news.sohu.com/20141126/n406399379.shtml
<<<<<<<<<<visiting:http://news.sohu.com/20141126/n406399379.shtml	depth=2
河北唐山现最牛婚礼 30多辆豪车价值超2亿(图)-搜狐新闻
2016-01-02 14:44:29 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - -activeThreads=1, spinWaiting=0, fetchQueue.size=138
2016-01-02 14:44:30 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - fetch URL: http://news.sohu.com/20150331/n410569699.shtml
<<<<<<<<<<visiting:http://news.sohu.com/20150331/n410569699.shtml	depth=2
盘点“低头族”?事：男子过铁道看手机逼停火车-搜狐新闻
2016-01-02 14:44:30 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - -activeThreads=1, spinWaiting=0, fetchQueue.size=137

**Comment by jinfanw** [comment]
代码我是31号更新的代码，应该是最新的

**Comment by hujunxianligong** [comment]
有个问题，我看你这个类叫SingleFetch，为什么实例化的时候是new Example()?

**Comment by jinfanw** [comment]
我这个是同一个代码，那个new example类太乱，我把没用的给删了放这个类里的

**Comment by jinfanw** [comment]
实例化的时候，new 成 SingleFetch 的实例就可以了，我刚才又跑了一下，改完singleFetch后的，还是不行。

package com.jintian.crawler;

import java.io.IOException;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.regex.Pattern;

import cn.edu.hfut.dmic.webcollector.model.CrawlDatum;
import cn.edu.hfut.dmic.webcollector.model.CrawlDatums;
import cn.edu.hfut.dmic.webcollector.model.Page;
import cn.edu.hfut.dmic.webcollector.plugin.berkeley.BreadthCrawler;
import cn.edu.hfut.dmic.webcollector.util.FileUtils;

public class SingerFetch extends BreadthCrawler{
	
	public SingerFetch(String crawlPath, boolean autoParse) {
		super(crawlPath, autoParse);
	}
	
	AtomicInteger id=new AtomicInteger(0);
	
	@Override
    public void visit(Page page, CrawlDatums next) {
		
        System.out.println("<<<<<<<<<<visiting:"+page.getUrl()+"\tdepth="+page.getMetaData("depth"));
        String title = page.select("title").first().text();
        System.out.println(title);
       }

    /* afterVisit方法在visit方法执行后执行，这里super.afterVisit完成根据
       正则自动抽取链接的功能，因此这里需要保留 */
    @Override
    public void afterVisit(Page page, CrawlDatums next) {
        super.afterVisit(page, next); 
        
        //当前页面的depth为x，则从当前页面解析的后续任务的depth为x+1
        int depth;
        //如果在添加种子时忘记添加depth信息，可以通过这种方式保证程序不出错
        if(page.getMetaData("depth")==null){
            depth=1;
        }else{
            depth=Integer.valueOf(page.getMetaData("depth"));
        }
        depth++;
        for(CrawlDatum datum:next){
            datum.putMetaData("depth", depth+"");
        }
    }
    
    public static void main(String[] args) throws Exception {
    	SingerFetch crawler=new SingerFetch("single_crawler", true);
       
        crawler.addSeed(new CrawlDatum("http://news.sohu.com/")
               .putMetaData("depth", "1"));

             
        crawler.addRegex(".*news.sohu.com/.*.shtml");
        crawler.setRetryInterval(1000);
        crawler.setVisitInterval(1000*1);
        crawler.setThreads(1);
        crawler.setResumable(true);

        crawler.start(3);
    }

}

**Comment by hujunxianligong** [comment]
你的代码在我机器运行是OK的，我改成多个线程快一些，你用我改过的代码再试试：

```

import java.io.IOException;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.regex.Pattern;

import cn.edu.hfut.dmic.webcollector.model.CrawlDatum;
import cn.edu.hfut.dmic.webcollector.model.CrawlDatums;
import cn.edu.hfut.dmic.webcollector.model.Page;
import cn.edu.hfut.dmic.webcollector.plugin.berkeley.BreadthCrawler;
import cn.edu.hfut.dmic.webcollector.util.FileUtils;

public class SingerFetch extends BreadthCrawler {

    public SingerFetch(String crawlPath, boolean autoParse) {
        super(crawlPath, autoParse);
    }

    AtomicInteger id = new AtomicInteger(0);

    @Override
    public void visit(Page page, CrawlDatums next) {

        System.out.println("<<<<<<<<<<visiting:" + page.getUrl() + "\tdepth=" + page.getMetaData("depth"));
        String title = page.select("title").first().text();
        System.out.println(title);
    }

    /* afterVisit方法在visit方法执行后执行，这里super.afterVisit完成根据
   正则自动抽取链接的功能，因此这里需要保留 */
    @Override
    public void afterVisit(Page page, CrawlDatums next) {
        super.afterVisit(page, next);

        //当前页面的depth为x，则从当前页面解析的后续任务的depth为x+1
        int depth;
        //如果在添加种子时忘记添加depth信息，可以通过这种方式保证程序不出错
        if (page.getMetaData("depth") == null) {
            depth = 1;
        } else {
            depth = Integer.valueOf(page.getMetaData("depth"));
        }
        depth++;
        for (CrawlDatum datum : next) {
            datum.putMetaData("depth", depth + "");
        }
    }

    public static void main(String[] args) throws Exception {
        SingerFetch crawler = new SingerFetch("single_crawler", true);

        crawler.addSeed(new CrawlDatum("http://news.sohu.com/")
                .putMetaData("depth", "1"));

        crawler.addRegex(".*news.sohu.com/.*.shtml");
//    crawler.setRetryInterval(1000);
//    crawler.setVisitInterval(1000*1);
        crawler.setThreads(100);
        crawler.setResumable(true);
        crawler.start(2);
    }
}

```

**Comment by hujunxianligong** [comment]
还有一个问题，如果你是断电、或者手动掐断，爬虫会重爬一小部分数据（也可以设置为不丢失，但是会加大硬盘写入频率）。正常断点是不会有问题的。我感觉你代码是手动掐断的吧？

**Comment by jinfanw** [comment]
第一次抓取正常，停止后再抓取报异常：

2016-01-02 15:11:52 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - Exception when updating db
java.lang.IllegalStateException: Can't call Database.put Database was closed.
	at com.sleepycat.je.Database.checkOpen(Database.java:1863)
	at com.sleepycat.je.Database.put(Database.java:1168)
	at cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBUtils.put(BerkeleyDBUtils.java:52)
	at cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBUtils.writeDatum(BerkeleyDBUtils.java:48)
	at cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBManager.wrtieFetchSegment(BerkeleyDBManager.java:108)
	at cn.edu.hfut.dmic.webcollector.fetcher.Fetcher$FetcherThread.run(Fetcher.java:286)
国际货币基金组织女掌门拉加德：愿与亚投行合作-搜狐新闻
2016-01-02 15:11:52 INFO cn.edu.hfut.dmic.webcollector.fetcher.Fetcher  - Exception when updating db
java.lang.IllegalStateException: Can't call Database.put Database was closed.
	at com.sleepycat.je.Database.checkOpen(Database.java:1863)
	at com.sleepycat.je.Database.put(Database.java:1168)
	at cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBUtils.put(BerkeleyDBUtils.java:52)
	at cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBUtils.writeDatum(BerkeleyDBUtils.java:48)
	at cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBManager.wrtieFetchSegment(BerkeleyDBManager.java:108)
	at cn.edu.hfut.dmic.webcollector.fetcher.Fetcher$FetcherThread.run(Fetcher.java:286)

**Comment by hujunxianligong** [comment]
1.停止所有爬虫进程。
2.删除single_crawler文件夹。
3.执行程序第一次等待进程结束。
4.第二次执行程序。

**Comment by jinfanw** [comment]
我不是抓取这个门户网站，主要是尝试下断点抓取功能。我这边有个网站的抓取不能开太多线程。而且容易中断。所以我才开了一个线程看看断点抓取的效果。

**Comment by hujunxianligong** [comment]
手动掐断会出现部分重爬，你把将BerkeleyDBManager的BUFFER_SIZE设置为1即可（不建议）设置成1用吧。BUFFER_SIZE是缓存大小，如果掐断爬虫这里面东西会丢。不过设置太小硬盘写入频率就比较快了。

**Comment by jinfanw** [comment]
还有一个问题：第一次执行的时候执行到  
2016-01-02 15:11:08 INFO cn.edu.hfut.dmic.webcollector.crawler.Crawler  - depth 2 finish: 
	TOTAL urls:	143
	TOTAL time:	14 seconds
就结束了


第二次执行程序，输出到depth 3 还没有结束。


第二次执行的深度是以
        crawler.addSeed(new CrawlDatum("http://news.sohu.com/")
                .putMetaData("depth", "1"));
这个seed为起点，还是以保存到库里的数据为起点？

**Comment by jinfanw** [comment]
那出现重拍可能是因为我手动掐断引起的。我每次都是爬取10多条就掐断了。

**Comment by hujunxianligong** [comment]
start里的参数虽然叫深度，实际是迭代次数，与拓扑深度没有任何关系。
深度是自己再metaData里修改的。

还有如果你真是那种频率很慢的爬虫，其实自己用HttpRequest写一个，然后随便找个redis或者mysql来做去重就OK了。断点爬虫主要面向页面较多网站设计的。

**Comment by jinfanw** [comment]
主要是想找一个比较稳定的，自己写会出现很多问题。过来学习下你的经验。
这个问题还是主要我使用不当引起的。
多谢指导。

**Comment by hujunxianligong** [comment]
单线程爬虫一般不会出什么问题，多加try catch就可以了。redis用来维护爬取历史比较方便。

**Comment by jinfanw** [comment]
问题确认了，确实是由于人为中断引起的，爬取完成后再重新启动就没有重复爬取的问题了。
再次感谢。

**Comment by jinfanw** [comment]
再问一个问题：
如果深度已经到达我预定的深度，例如我的深度为2，再我第二次重新启动执行后，怎么让
 crawler.start(2);  这里定义的迭代次数提前结束？

**Comment by hujunxianligong** [comment]
你在往next里添加任务时，超过期望层数的就不要添加。
爬虫没有任务可执行时会自动停止。

**Comment by jinfanw** [comment]
好的，我再学习一下。很多功能不会用。
多谢。

**Comment by jinfanw** [comment]
还是深度的问题，这样一个场景：
第一次爬取查询正常结束，深度为2，迭代次数也是2。第二次我接着上次结果运行，迭代次数为2，深度为2的不再进行爬取，但我每次运行时，next里都会有任务加载进去，如何让深度为2的链接不作为seed加载进next。

我在visit里加了一个深度的判断，但是运行时是先进行了抓取，才进入visit方法。
如何让在二次启动时，深度为2的不加入的next里。


  @Override
    public void visit(Page page, CrawlDatums next) {

        System.out.println("<<<<<<<<<<visiting:" + page.getUrl() + "\tdepth=" + page.getMetaData("depth"));
        String title = page.select("title").first().text();
        System.out.println(title);
        if(Integer.valueOf(page.getMetaData("depth"))>=2){
        	next.clear();
        }
    }

**Comment by hujunxianligong** [comment]
把autoparse关掉（构造函数第二个参数），自己把需要的任务添加到next中即可。

**Comment by jinfanw** [comment]
我可能没说明白，第二次启动后的抓取任务我觉得是默认把之前抓的数据做为了启动后任务的起点。
我现在还没有到往next里添加任务的步骤。
把autoparse关掉后还是会出现深度为3的日志输出。

**Comment by jinfanw** [comment]
我错了，是可以的
