### ISSUE TITLE
你好！ LockTimeoutException

### ISSUE THREAD

**Issue by simplecnst** [CrawlScript/WebCollector#92]
你好，报这个错，怎么解决呢？
com.sleepycat.je.LockTimeoutException: (JE 5.0.73) Lock expired. Locker 264328825 -1_Thread-7381_ThreadLocker: waited for lock on database=_jeNameMap LockAddr:556941658 LSN=0x0/0x9ef type=WRITE grant=WAIT_PROMOTION timeoutMillis=500 startTime=1535089847412 endTime=1535089847912 Owners: [, ] Waiters: [] Transaction 264328825 -1_Thread-7381_ThreadLocker owns LockAddr:556941658 Transaction 264328825 -1_Thread-7381_ThreadLocker waits for LockAddr:556941658

at com.sleepycat.je.txn.LockManager.newLockTimeoutException(LockManager.java:664)
at com.sleepycat.je.txn.LockManager.makeTimeoutMsgInternal(LockManager.java:623)
at com.sleepycat.je.txn.SyncedLockManager.makeTimeoutMsg(SyncedLockManager.java:97)
at com.sleepycat.je.txn.LockManager.lockInternal(LockManager.java:390)
at com.sleepycat.je.txn.LockManager.lock(LockManager.java:276)
at com.sleepycat.je.txn.BasicLocker.lockInternal(BasicLocker.java:118)
at com.sleepycat.je.txn.Locker.lock(Locker.java:443)
at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:2621)
at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:2422)
at com.sleepycat.je.dbi.CursorImpl.searchAndPosition(CursorImpl.java:2150)
at com.sleepycat.je.dbi.CursorImpl.searchAndPosition(CursorImpl.java:2020)
at com.sleepycat.je.dbi.DbTree.lockNameLN(DbTree.java:880)
at com.sleepycat.je.dbi.DbTree.doRemoveDb(DbTree.java:1099)
at com.sleepycat.je.dbi.DbTree.dbRemove(DbTree.java:1152)
at com.sleepycat.je.Environment.removeDatabase(Environment.java:963)
at cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBManager.merge(BerkeleyDBManager.java:197)
at cn.edu.hfut.dmic.webcollector.fetcher.Fetcher.fetchAll(Fetcher.java:305)
at cn.edu.hfut.dmic.webcollector.crawler.Crawler.start(Crawler.java:136)
at com.app.MatchURLThread.run(MatchURLThread.java:90)

**Comment by hujunxianligong** [comment]
已经添加了RocksDB内核，可以试试
import cn.edu.hfut.dmic.webcollector.plugin.rocks.BreadthCrawler;
